# Generated by Django 5.2.7 on 2025-10-31 07:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0007_victim_dob_victim_gender_victim_mobile_victim_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_date', models.DateField()),
                ('incident_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('suspect_details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='fir.victim')),
            ],
        ),
    ]
