# Generated by Django 5.2.7 on 2025-10-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0008_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
