# Generated by Django 5.2.7 on 2025-11-05 12:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0009_complaint_complaint_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='id',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='incident_date',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='incident_time',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='status',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='suspect_details',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='victim',
        ),
        migrations.AddField(
            model_name='complaint',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='complaint',
            name='delay',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='complaint',
            name='subCategory',
            field=models.CharField(default='Other', max_length=100),
        ),
        migrations.AddField(
            model_name='complaint',
            name='time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='victim_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
