# Generated by Django 5.2.7 on 2026-03-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0012_complaint_notification_timeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('faceShape', models.CharField(max_length=50)),
                ('skinTone', models.CharField(max_length=50)),
                ('forehead', models.CharField(max_length=50)),
                ('hairType', models.CharField(max_length=50)),
                ('hairColor', models.CharField(max_length=50)),
                ('eyeShape', models.CharField(max_length=50)),
                ('eyeColor', models.CharField(max_length=50)),
                ('eyebrow', models.CharField(max_length=50)),
                ('noseSize', models.CharField(max_length=50)),
                ('noseShape', models.CharField(max_length=50)),
                ('lipType', models.CharField(max_length=50)),
                ('beard', models.CharField(max_length=50)),
                ('mustache', models.CharField(max_length=50)),
                ('identifiers', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
