# Generated by Django 5.2.7 on 2026-03-28 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0013_suspect'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspect',
            name='complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fir.complaint'),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='age',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='gender',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='identifiers',
            field=models.TextField(blank=True),
        ),
    ]
