# Generated by Django 5.2.7 on 2026-03-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0014_suspect_complaint_alter_suspect_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspect',
            name='identifiers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
