# Generated by Django 5.0.6 on 2026-04-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0015_alter_suspect_identifiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspect',
            name='sketch_audit_trail',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='suspect',
            name='sketch_image',
            field=models.ImageField(blank=True, null=True, upload_to='sketches/'),
        ),
    ]
